version: '3'

services:
  auth-service:
    platform: 'linux/amd64'
    image: 'auth-service:latest'
    container_name: auth-service
    build:
      context: auth-service
      dockerfile: Dockerfile
    depends_on:
      - user-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-db:5432/user_db
      - SPRING_DATASOURCE_USERNAME=numanarif
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8085
    expose:
      - "8081"
    ports:
      - "8081:8081"

  user-db:
    image: 'mysql:8.0'
    container_name: user-db
    environment:
      - MYSQL_USER=user_db
      - MYSQL_PASSWORD=user_db
      - MYSQL_DB=user_db
    volumes:
      - user_db:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  user_db:

