version: '3'

services:
  gateway-service:
    platform: 'linux/amd64'
    image: 'gateway-service:latest'
    container_name: gateway-service
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
  auth-service:
    platform: 'linux/amd64'
    image: 'auth-service:latest'
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    depends_on:
      - user-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-db:3306/user_db
      - SPRING_DATASOURCE_USERNAME=user_db
      - SPRING_DATASOURCE_PASSWORD=user_db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8081
    expose:
      - "8081"
    ports:
      - "8081:8081"
  rabbitmq-producer-service:
    platform: 'linux/amd64'
    image: 'rabbitmq-producer-service:latest'
    container_name: rabbitmq-producer-service
    build:
      context: ./rabbitmq-producer-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_RABBITMQ_VIRTUAL-host=/
    expose:
      - "8084"
    ports:
      - "8084:8084"
  rabbitmq-consumer-service:
    platform: 'linux/amd64'
    image: 'rabbitmq-consumer-service:latest'
    container_name: rabbitmq-consumer-service
    build:
      context: ./rabbitmq-consumer-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      #      port for amqp(advance message queueing protocol)
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_RABBITMQ_VIRTUAL-host=
    expose:
      - "8086"
    ports:
      - "8086:8086"
  project-service:
    platform: 'linux/amd64'
    image: 'project-service:latest'
    container_name: project-service
    build:
      context: ./project-service
      dockerfile: Dockerfile
    depends_on:
      - project-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://project-db:3306/project_db
      - SPRING_DATASOURCE_USERNAME=project_db
      - SPRING_DATASOURCE_PASSWORD=project_db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8082
    expose:
      - "8082"
    ports:
      - "8082:8082"
  task-service:
    platform: 'linux/amd64'
    image: 'task-service:latest'
    container_name: task-service
    build:
      context: ./task-service
      dockerfile: Dockerfile
    depends_on:
      - task-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://task-db:3306/task_db
      - SPRING_DATASOURCE_USERNAME=task_db
      - SPRING_DATASOURCE_PASSWORD=task_db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8083
    expose:
      - "8083"
    ports:
      - "8083:8083"
  user-db:
    image: 'mysql:8.0'
    container_name: user-db
    environment:
      - MYSQL_USER=user_db
      - MYSQL_PASSWORD=user_db
      - MYSQL_DATABASE=user_db
    volumes:
      - user_db:/var/lib/mysql/data
    ports:
      - "3306:3306"
  project-db:
    image: 'mysql:8.0'
    container_name: project-db
    environment:
      - MYSQL_USER=user_db
      - MYSQL_PASSWORD=user_db
      - MYSQL_DATABASE=user_db
    volumes:
      - project_db:/var/lib/mysql/data
    ports:
      - "3307:3307"
  task-db:
    image: 'mysql:8.0'
    container_name: task-db
    environment:
      - MYSQL_USER=user_db
      - MYSQL_PASSWORD=user_db
      - MYSQL_DATABASE=user_db
    volumes:
      - task_db:/var/lib/mysql/data
    ports:
      - "3308:3308"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-local'
    expose:
      - "15672"
      - "5672"
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbit_mq1:/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - rabbit_mq2:/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
volumes:
  user_db:
  project_db:
  task_db:
  rabbit_mq1:
  rabbit_mq2: