### Add Product
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "name" : "Bakso Malang",
  "description" : "Bakso Kuah",
  "stock" : 100,
  "price" : 10000
}

### GET All Products
GET http://localhost:8080/api/v1/products
Accept: application/json


### GET All Products
PUT http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "id" : 1,
  "name" : "Bakso Presiden",
  "description" : "Bakso Kuah",
  "stock" : 100,
  "price" : 10000
}

### Delete Prod
DELETE http://localhost:8080/api/v1/products/4
