### Add Product
POST http://ikoncrudaws-env.eba-w5kpiwmn.ap-northeast-1.elasticbeanstalk.com/api/v1/products
Content-Type: application/json

{
  "name" : "Indomie",
  "description" : "Indomie goreng",
  "stock" : 1000,
  "price" : 2000
}

### GET All Products
GET http://ikoncrudaws-env.eba-w5kpiwmn.ap-northeast-1.elasticbeanstalk.com/api/v1/products
Accept: application/json


###
PUT http://ikoncrudaws-env.eba-w5kpiwmn.ap-northeast-1.elasticbeanstalk.com/api/v1/products
Content-Type: application/json

{
  "id" : 1,
  "name" : "Bakso Sapi",
  "description" : "Bakso Kuah",
  "stock" : 100,
  "price" : 10000
}

### Delete Prod
DELETE http://ikoncrudaws-env.eba-w5kpiwmn.ap-northeast-1.elasticbeanstalk.com/api/v1/products/4
