POST localhost:8081/api/v2/auth/register
Content-Type: application/json

{
  "username" : "Admin",
  "email" : "Admin@gmail.com",
  "password" : "Arif@22222",
  "phone" : 33333,
  "name" : "Arif Tes",
  "role" : "admin"
}
###

POST localhost:8081/api/v2/auth/login
Content-Type: application/json

{
  "phone" : 33333,
  "password" : "Arif@22222"
}
> {% client.global.set("auth_token", response.body.data); %}
###
GET localhost:8081/api/v2/auth/user-data
Authorization: Bearer {{auth_token}}


###
#
#POST localhost:8081/api/v1/auth/login
#Content-Type: application/json
#
#{
#  "username" : "arif",
#  "password" : "12345"
#}