on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: compile
        run: |
          cd user-service
          mvn compile
      - name: test
        run: |
          cd user-service
          mvn test

      - name: Configure Certificate
        env:
          DOCKER_CA: ${{ vars.VAR_DOCKER_CA }}
          DOCKER_CERT: ${{ vars.VAR_DOCKER_CERT }}
          DOCKER_KEY: ${{ vars.VAR_DOCKER_KEY }}
          DOCKER_HOST: "ec2-13-113-140-77.ap-northeast-1.compute.amazonaws.com:2376"
          DOCKER_TLS_VERIFY: 1
        run: |
          sudo mkdir -pv /home/runner/.docker
          echo "$DOCKER_CA" > /home/runner/.docker/ca.pem
          echo "$DOCKER_CERT" > /home/runner/.docker/cert.pem
          echo "$DOCKER_KEY" > /home/runner/.docker/key.pem
          make
